version: '3.9'

networks:
  prometheus_network:
    driver: bridge
    ipam:
      driver: default

services:
  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - prometheus_network
    ports:
      - "9090:9090"

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:latest
    # volumes:
    #   - ./configs/blackbox-exporter.yml:/etc/blackbox_exporter/config.yml
    container_name: blackbox-exporter
    networks:
      - prometheus_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - prometheus_network
    ports:
      - "3000:3000"
