version: '3.9'

services:
  prometheus:
    image: bitnami/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    ports:
      - "9090:9090"

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:latest
    # volumes:
    #   - ./configs/blackbox-exporter.yml:/etc/blackbox_exporter/config.yml
    container_name: blackbox-exporter

  grafana:
    image: grafana/grafana:6.7.4
    container_name: grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN
    command: http grafana:3000
    ports:
      - "4040:4040"
